L2J/L2J_DataPack

L2J_DataPack/dist/game/data/html/teleporter/30006-1.htm, L2J_DataPack/dist/game/data/html/teleporter/30006-2.htm, L2J_DataPack/dist/game/data/html/teleporter/30006-3.htm, L2J_DataPack/dist/game/data/html/teleporter/30006-4.htm, L2J_DataPack/dist/game/data/html/teleporter/30006-5.htm, L2J_DataPack/dist/game/data/html/teleporter/30006.htm, L2J_DataPack/dist/game/data/scripts.cfg, L2J_DataPack/dist/game/data/scripts/ai/npc/Milia/Milia.java, L2J_DataPack/dist/game/data/teleporters/Elisa.xml, L2J_DataPack/dist/game/data/teleporters/Milia.xml
=> Reworked teleporter in Talking Island Village and fixed price of

L2J_DataPack/dist/game/data/scripts/ai/npc/CastleBlacksmith/35272-02.html, L2J_DataPack/dist/game/data/scripts/ai/npc/CastleBlacksmith/35361-01.html, L2J_DataPack/dist/game/data/scripts/ai/npc/CastleBlacksmith/35361-02.html, L2J_DataPack/dist/game/data/scripts/ai/npc/CastleBlacksmith/35507-01.html, L2J_DataPack/dist/game/data/scripts/ai/npc/CastleBlacksmith/35507-02.html, L2J_DataPack/dist/game/data/scripts/ai/npc/CastleBlacksmith/35553-01.html, L2J_DataPack/dist/game/data/scripts/ai/npc/CastleBlacksmith/35553-02.html
=> Fixing another typos in Castle Blacksmith

L2J_DataPack/dist/game/config/adminCommands.xml, L2J_DataPack/dist/game/data/scripts/ai/npc/Mammons/Mammons.java, L2J_DataPack/dist/game/data/scripts/handlers/admincommandhandlers/AdminTeleport.java
function in alt+g) and removed debug message in mammon AI.
=> Added admin command //teleport X, Y, Z (required by Search Quest

L2J_DataPack/dist/game/data/scripts/quests/Q00215_TrialOfThePilgrim/Q00215_TrialOfThePilgrim.java
Missing HTML page: data/scripts/quests/Q00215_TrialOfThePilgrim/30648-4a.htm
=> "My HTML is missing"

L2J_DataPack/dist/game/data/scripts/handlers/admincommandhandlers/AdminTeleport.java
admin_teleport since is used startsWith method)
=> Fixed admin teleport to player (admin_teleportto should be before

L2J_DataPack/dist/game/data/scripts.cfg, L2J_DataPack/dist/game/data/scripts/ai/npc/AlchemistManager/33977-1.html, L2J_DataPack/dist/game/data/scripts/ai/npc/AlchemistManager/33977-2.html, L2J_DataPack/dist/game/data/scripts/ai/npc/AlchemistManager/33977.html, L2J_DataPack/dist/game/data/scripts/ai/npc/AlchemistManager/33978-1.html, L2J_DataPack/dist/game/data/scripts/ai/npc/AlchemistManager/33978-2.html, L2J_DataPack/dist/game/data/scripts/ai/npc/AlchemistManager/33978.html, L2J_DataPack/dist/game/data/scripts/ai/npc/AlchemistManager/AlchemistManager.java
=> Reworked Zephyra AI to handle more npc's whit same type (also renamed to

L2J_DataPack/dist/game/data/html/admin/teleports/instance.htm, L2J_DataPack/dist/game/data/instancenames.xml, L2J_DataPack/dist/game/data/scripts.cfg, L2J_DataPack/dist/game/data/scripts/ai/npc/Acateo/33905-1.html, L2J_DataPack/dist/game/data/scripts/ai/npc/Acateo/33905-2.html, L2J_DataPack/dist/game/data/scripts/ai/npc/Acateo/33905-3.html, L2J_DataPack/dist/game/data/scripts/ai/npc/Acateo/33905.html, L2J_DataPack/dist/game/data/scripts/ai/npc/Acateo/Acateo.java
Nothing epic, skills/items are not commited cause of conflicts after some changes...
=> Adding Acateo AI and minor fixes

L2J_DataPack/dist/game/data/skillTrees/TyrrGrandKhavatari.xml
Because he replace to Force Storm and Raging Force in Ertheia
=> Delete unused skills in Ertheia

L2J_DataPack/dist/game/data/multisell/311262509.xml, L2J_DataPack/dist/game/data/multisell/779.xml, L2J_DataPack/dist/game/data/scripts/ai/npc/Mammons/31126-01.html
- Added Special Ability for R+ grade weapons
=> Updated npc Blacksmith of Mammon

L2J_DataPack/dist/game/data/stats/skills/11800-11899.xml
L2J/L2J_DataPack@2372859ad2958e9e807b79988f03b4413307b2b9
Reported by: @Battlecruiser
=> Fixed tipo from

L2J_DataPack/dist/game/data/mapregion/faeron_town.xml, L2J_DataPack/dist/game/data/mapregion/talking_island_town.xml, L2J_DataPack/dist/game/data/zones/peace.xml, L2J_DataPack/dist/game/data/zones/respawn.xml
=> Added peace zone to faenor and added respawn points to feanor village

L2J_DataPack/dist/game/data/xsd/skills.xsd
L2J/L2J_DataPack@371e670a6e155866bf5bca7231a4203e05cbffdf
=> Updates skills.xsd after

L2J_DataPack/dist/game/data/scripts/ai/npc/Proclaimer/Proclaimer.java, L2J_DataPack/dist/game/data/scripts/handlers/MasterHandler.java, L2J_DataPack/dist/game/data/scripts/handlers/admincommandhandlers/AdminAdmin.java, L2J_DataPack/dist/game/data/scripts/handlers/chathandlers/ChatGeneral.java, L2J_DataPack/dist/game/data/scripts/handlers/chathandlers/ChatWhisper.java, L2J_DataPack/dist/game/data/scripts/handlers/chathandlers/ChatWorld.java, L2J_DataPack/dist/game/data/scripts/handlers/telnethandlers/ChatsHandler.java, L2J_DataPack/dist/game/data/scripts/instances/DisciplesNecropolisPast/DisciplesNecropolisPast.java, L2J_DataPack/dist/game/data/scripts/instances/HarnakUndergroundRuins/HarnakUndergroundRuins.java, L2J_DataPack/dist/game/data/scripts/quests/Q00457_LostAndFound/Q00457_LostAndFound.java
L2J/L2J_Server@f276f4e865c797715bf12e89937919bdaa9d09b4
=> Datapack-part for

L2J_DataPack/dist/game/data/scripts/quests/Q00292_BrigandsSweep/Q00292_BrigandsSweep.java
=> dialog fix for Q00292

L2J_DataPack/dist/game/data/html/teleporter/half/30080.htm
=> minor fix typo

L2J_DataPack/dist/game/data/stats/npcs/18800-18900.xml
with forgotten scrolls 81-82 lvls
=> Rework droplist for Beast Farm

L2J_DataPack/dist/game/data/stats/skills/11500-11599.xml
Superior Dual Weapon Mastery
Superior Robe Mastery
Superior Light Armor Mastery
Superior Heavy Armor Mastery
Superior Anti Magic
Superior HP Boost
Superior MP Boost
Crippling Attack
Shadow Blade
Death Strike
Horn Melody
Drum Melody
Pipe Organ Melody
Guitar Melody
Harp Melody
Lute Melody
Knight's Harmony
Warrior's Harmony
Wizard's Harmony
Prevailing Sonata
Daring Sonata
Refreshing Sonata
Superior HP Recovery
Superior Quick Recovery
Superior Mental Attack Resistance
Superior Divine Lore
Superior Focus Mind
Superior Sixth Sense
Superior Fast Spell Casting
Elemental Resistance
Holy Attack Resistance
Mental Attack Resistance
Critical Damage Increase
Superior Advantage
=> Added few Iss skills

L2J_DataPack/dist/game/data/stats/npcs/22600-22700.xml
for Field of Whispers and Field of Silence
=> Rework droplist

L2J_DataPack/dist/game/data/stats/npcs/22800-22900.xml
Mutual Response for Divinity Magus
=> Add drop forgotten scroll

L2J_DataPack/dist/game/data/scripts/hellbound/AI/Zones/TowerOfNaia/TowerOfNaia.java
Tower of Naia:
* NPE in spore challenge fixed
* Unnecesary timers canceled
1) Enter in Tower of Naia (Hellbound lvl 11) and go to Spore challenge
2) Kill only one type of spore. Epidos should spawn after killing several mobs.
http://www.l2jserver.com/forum/viewtopic.php?f=77&t=31387
http://www.l2jserver.com/forum/viewtopic.php?f=77&t=31290
Reported by: CostyKiller, u3games
Thank you!
=> Tower of Naia fixes

L2J_DataPack/dist/game/data/scripts/ai/individual/Baium/Baium.java
Problem: A bug when Baium wakes up for the second time with another player, it stays with AI disabled.
Solution: when it's need it, get a random player if the first target is not near, he is dead or disconnected.
Extra: NpcStringId implemented and unnecessary quest timers canceled
1) Wake up Baium and let it kills you.
2) Wait for Baium sleep (30 minutes without attack it).
3) Wake up Baium with different player. It should says player's name and kill him.
http://www.l2jserver.com/forum/viewtopic.php?f=77&t=31171
Thank you for the report sahar!
=> Baium AI fixed

dist/game/data/scripts/handlers/effecthandlers/MagicalAttack.java
Datapack part of L2J/L2J_Server@7290304083d40fdecb6d5e004db2b303b1e3306a
http://www.l2jserver.com/forum/viewtopic.php?f=77&t=29713
**Reported by** Zephyr
=> Fix suicide skills

dist/game/data/scripts/village_master/OrcChange1/OrcChange1.java
Wrong item id for MASK_OF_MEDIUM.
=> Minor typo in OrcChange1.java
